-- Insert products
INSERT INTO products (name, description, price, original_price, category, image_url, featured, is_new, on_sale, discount, rating)
VALUES 
    ('WOEM', 
     'Elegant ladies watch with rose gold finish. Features a sophisticated design with premium materials and precise timekeeping mechanism. Perfect for both casual and formal occasions.',
     15000,
     1400,
     'ladies-watch',
     'https://hjbynsyoyipnwovkytrm.supabase.co/storage/v1/object/public/images/0mmjj51p2pmp.jpg',
     true,
     true,
     true,
     45,
     0),

    ('RM',
     'Premium men''s watch with modern design. Features a durable stainless steel case, precise automatic movement, and water resistance. Ideal for everyday wear.',
     20000,
     5000,
     'mens-watch',
     'https://hjbynsyoyipnwovkytrm.supabase.co/storage/v1/object/public/images/rm.jpg',
     true,
     false,
     true,
     30,
     0),

    ('sunglass',
     'Designer sunglasses with UV protection. Features premium quality lenses, comfortable fit, and stylish design. Perfect for both fashion and eye protection.',
     14000,
     5000,
     'sunglasses',
     'https://hjbynsyoyipnwovkytrm.supabase.co/storage/v1/object/public/images/sunglass.jpg',
     false,
     true,
     true,
     20,
     0),

    ('rolex',
     'Luxury men''s watch with classic design. Features premium materials, automatic movement, and elegant styling. A timeless piece for the discerning gentleman.',
     15000,
     4500,
     'mens-watch',
     'https://hjbynsyoyipnwovkytrm.supabase.co/storage/v1/object/public/images/rolex.jpg',
     true,
     true,
     false,
     0,
     0); 